http {
    upstream api {
        server api:8080;
        server auth:5000;
        server billing:6000;
        server user_management:7000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://api/;
        }

        location /auth/ {
            proxy_pass http://auth/;
        }

        location /billing/ {
            proxy_pass http://billing/;
        }

        location /user_management/ {
            proxy_pass http://user_management/;
        }
    }
}
