import { type ExpensePattern } from './fixedExpenseDetectorTypes';

export const FIXED_PATTERNS: ExpensePattern[] = [
  { name: 'Aluguel', keywords: ['aluguel', 'locação', 'locacao', 'arrendamento'], category: 'housing', logo: '🏠', min_amount: 200 },
  { name: 'Condomínio', keywords: ['condomínio', 'condominio', 'taxa cond'], category: 'housing', logo: '🏢', min_amount: 50 },
  { name: 'IPTU', keywords: ['iptu', 'imposto predial'], category: 'housing', logo: 'ðŸ›ï¸', min_amount: 30 },
  { name: 'Financiamento Imóvel', keywords: ['financiamento imóvel', 'financiamento imovel', 'prestação imóvel', 'prestacao imovel', 'caixa habitação', 'habitacao', 'caixa hab'], category: 'housing', logo: '🔑', min_amount: 200 },
  { name: 'Energia Elétrica', keywords: ['cemig', 'copel', 'light', 'enel', 'elektro', 'coelba', 'celpe', 'ampla', 'energia', 'conta de luz', 'eletricidade'], category: 'utilities', logo: '⚡', min_amount: 30 },
  { name: 'Água / Saneamento', keywords: ['sabesp', 'saneamento', 'copasa', 'embasa', 'caesb', 'cagece', 'água', 'agua', 'sanepar'], category: 'utilities', logo: '💧', min_amount: 20 },
  { name: 'Gás', keywords: ['comgás', 'comgas', 'copergás', 'copergas', 'gas natural', 'gas encanado', 'gás'], category: 'utilities', logo: '🔥', min_amount: 20 },
  { name: 'Internet', keywords: ['claro net', 'vivo fibra', 'oi fibra', 'tim fibra', 'net virtua', 'internet', 'banda larga', 'wifi'], category: 'utilities', logo: 'ðŸŒ', min_amount: 50 },
  { name: 'Telefone Fixo', keywords: ['telefone fixo', 'conta telefone', 'oi telefone'], category: 'utilities', logo: 'ðŸ“ž', min_amount: 20 },
  { name: 'Plano de Saúde', keywords: ['amil', 'unimed', 'hapvida', 'notre dame', 'sulamerica saude', 'bradesco saude', 'plano saúde', 'plano saude', 'plano de saúde'], category: 'insurance', logo: '🏥', min_amount: 80 },
  { name: 'Seguro Auto', keywords: ['porto seguro', 'bradesco auto', 'itaú seguro', 'seguro veículo', 'seguro veiculo', 'seguro auto'], category: 'insurance', logo: '🚗', min_amount: 50 },
  { name: 'Seguro Vida', keywords: ['seguro de vida', 'vida metlife', 'tokio marine vida'], category: 'insurance', logo: 'ðŸ›¡ï¸', min_amount: 30 },
  { name: 'Seguro Residencial', keywords: ['seguro residencial', 'seguro lar', 'seguro casa'], category: 'insurance', logo: 'ðŸ¡', min_amount: 20 },
  { name: 'Escola / Colégio', keywords: ['mensalidade escolar', 'mensalidade colegio', 'colégio', 'colegio', 'escola'], category: 'education', logo: '🏫', min_amount: 100 },
  { name: 'Faculdade / Universidade', keywords: ['mensalidade faculdade', 'universidade', 'anhanguera', 'kroton', 'estácio', 'estacio', 'unopar', 'unip', 'usp', 'unicamp', 'ufrj'], category: 'education', logo: '🎓', min_amount: 100 },
  { name: 'Curso Online', keywords: ['coursera', 'udemy', 'alura', 'hotmart', 'kiwify', 'edx'], category: 'education', logo: 'ðŸ’»', min_amount: 20 },
  { name: 'Academia', keywords: ['smart fit', 'academia', 'bluefit', 'bodytech', 'crossfit', 'gympass', 'wellhub'], category: 'fitness', logo: 'ðŸ’ª', min_amount: 40 },
  { name: 'Pilates / Yoga', keywords: ['pilates', 'yoga', 'estúdio'], category: 'fitness', logo: '🧘', min_amount: 80 },
  { name: 'Estacionamento Mensal', keywords: ['estacionamento mensal', 'mensalista', 'vaga garagem'], category: 'transport', logo: 'ðŸ…¿ï¸', min_amount: 80 },
  { name: 'Transporte Público', keywords: ['bilhete único', 'cartão transporte', 'vale transporte', 'metrô', 'metro', 'ônibus', 'onibus'], category: 'transport', logo: '🚌', min_amount: 50 },
  { name: 'Financiamento Veículo', keywords: ['financiamento veículo', 'financiamento veiculo', 'parcela carro', 'consórcio auto', 'consorcio auto'], category: 'financing', logo: '🚙', min_amount: 200 },
  { name: 'Crédito Pessoal', keywords: ['empréstimo', 'emprestimo', 'crédito pessoal', 'credito pessoal', 'parcela empréstimo'], category: 'financing', logo: '💳', min_amount: 100 },
  { name: 'Consórcio', keywords: ['consórcio', 'consorcio'], category: 'financing', logo: '🤝', min_amount: 100 },
  { name: 'Netflix', keywords: ['netflix'], category: 'subscription', logo: '🎬', min_amount: 15 },
  { name: 'Spotify', keywords: ['spotify'], category: 'subscription', logo: '🎵', min_amount: 10 },
  { name: 'Disney+', keywords: ['disney'], category: 'subscription', logo: '🏰', min_amount: 15 },
];

