import { type KnownService } from './subscriptionDetectorTypes';

export const KNOWN_SERVICES: KnownService[] = [
  { name: 'Netflix', keywords: ['netflix'], category: 'Entretenimento', logo: '🎬', typical_range: [20, 60] },
  { name: 'Disney+', keywords: ['disney', 'disney+'], category: 'Entretenimento', logo: '🏰', typical_range: [15, 40] },
  { name: 'HBO Max', keywords: ['hbo', 'max', 'warner'], category: 'Entretenimento', logo: '📺', typical_range: [20, 50] },
  { name: 'Amazon Prime', keywords: ['amazon prime', 'prime video'], category: 'Entretenimento', logo: '📦', typical_range: [10, 30] },
  { name: 'Globoplay', keywords: ['globoplay', 'globo play'], category: 'Entretenimento', logo: '🌐', typical_range: [15, 40] },
  { name: 'Paramount+', keywords: ['paramount'], category: 'Entretenimento', logo: '🎭', typical_range: [15, 35] },
  { name: 'Apple TV+', keywords: ['apple tv'], category: 'Entretenimento', logo: '🍎', typical_range: [20, 40] },
  { name: 'Spotify', keywords: ['spotify'], category: 'Entretenimento', logo: '🎵', typical_range: [10, 30] },
  { name: 'Apple Music', keywords: ['apple music', 'itunes'], category: 'Entretenimento', logo: '🎶', typical_range: [10, 30] },
  { name: 'Deezer', keywords: ['deezer'], category: 'Entretenimento', logo: '🎧', typical_range: [10, 25] },
  { name: 'YouTube Music', keywords: ['youtube', 'youtube premium'], category: 'Entretenimento', logo: '▶️', typical_range: [15, 35] },
  { name: 'Google One', keywords: ['google one', 'google storage'], category: 'Tecnologia', logo: '☁️', typical_range: [5, 40] },
  { name: 'iCloud', keywords: ['icloud', 'apple icloud'], category: 'Tecnologia', logo: '🍎', typical_range: [5, 35] },
  { name: 'Microsoft 365', keywords: ['microsoft 365', 'office 365', 'ms office'], category: 'Tecnologia', logo: '💻', typical_range: [20, 70] },
  { name: 'Dropbox', keywords: ['dropbox'], category: 'Tecnologia', logo: '📂', typical_range: [10, 50] },
  { name: 'Adobe CC', keywords: ['adobe', 'creative cloud'], category: 'Tecnologia', logo: '🎨', typical_range: [50, 300] },
  { name: 'Notion', keywords: ['notion'], category: 'Tecnologia', logo: '📝', typical_range: [10, 50] },
  { name: 'Canva', keywords: ['canva'], category: 'Tecnologia', logo: '🖼️', typical_range: [10, 80] },
  { name: 'Smart Fit', keywords: ['smart fit', 'smartfit'], category: 'Saúde', logo: '💪', typical_range: [50, 120] },
  { name: 'Gympass', keywords: ['gympass', 'wellhub'], category: 'Saúde', logo: '🏋️', typical_range: [50, 200] },
  { name: 'Headspace', keywords: ['headspace'], category: 'Saúde', logo: '🧘', typical_range: [20, 50] },
  { name: 'Calm', keywords: ['calm'], category: 'Saúde', logo: '🌿', typical_range: [20, 50] },
  { name: 'iFood', keywords: ['ifood'], category: 'Alimentação', logo: '🍔', typical_range: [20, 50] },
  { name: 'Rappi Turbo', keywords: ['rappi turbo', 'rappiturbo'], category: 'Alimentação', logo: '🛵', typical_range: [10, 30] },
  { name: 'New York Times', keywords: ['nytimes', 'new york times'], category: 'Informação', logo: '📰', typical_range: [10, 40] },
  { name: 'Medium', keywords: ['medium.com', 'medium'], category: 'Informação', logo: '✍️', typical_range: [10, 30] },
  { name: 'Claro', keywords: ['claro'], category: 'Telecomunicações', logo: '📱', typical_range: [30, 200] },
  { name: 'Vivo', keywords: ['vivo'], category: 'Telecomunicações', logo: '📡', typical_range: [30, 200] },
  { name: 'TIM', keywords: ['tim'], category: 'Telecomunicações', logo: '📶', typical_range: [30, 200] },
  { name: 'NET/Claro', keywords: ['net ', 'net internet'], category: 'Telecomunicações', logo: '🌐', typical_range: [80, 250] },
  { name: 'Sulamerica', keywords: ['sulamerica', 'sul america'], category: 'Seguros', logo: '🛡️', typical_range: [50, 500] },
  { name: 'Bradesco Saúde', keywords: ['bradesco saude', 'bradesco saúde'], category: 'Seguros', logo: '🏥', typical_range: [100, 800] },
  { name: 'Unimed', keywords: ['unimed'], category: 'Seguros', logo: '⚕️', typical_range: [100, 800] },
  { name: 'Amil', keywords: ['amil'], category: 'Seguros', logo: '🩺', typical_range: [100, 800] },
  { name: 'LinkedIn Premium', keywords: ['linkedin'], category: 'Carreira', logo: '💼', typical_range: [30, 150] },
  { name: 'Coursera', keywords: ['coursera'], category: 'Educação', logo: '🎓', typical_range: [20, 200] },
  { name: 'Duolingo Plus', keywords: ['duolingo'], category: 'Educação', logo: '🦉', typical_range: [10, 30] },
];
